### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by teohhanhui**
- Rename driver from `Fetch` to `HTTP`
- Add example with `input` and `init`

### CODE REVIEW

**Comment by teohhanhui** [comment]
@secobarbital Since you've made the changes for the first item, I'll open a separate PR once you've merged in your commit.

**Comment by teohhanhui** [comment]
Also, I want to provide a reference to the [documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch), but I'm concerned that we don't support `input` as string. I think we should change that.

**Comment by secobarbital** [comment]
We do support `input` as string, actually.

**Comment by teohhanhui** [comment]
[src/index.js#L8](https://github.com/cyclejs/cycle-fetch-driver/blob/d2bae7eeaa9d0b29f1bc5f62f4b3686b5a966f35/src/index.js#L8)
and
[src/index.js#L22](https://github.com/cyclejs/cycle-fetch-driver/blob/d2bae7eeaa9d0b29f1bc5f62f4b3686b5a966f35/src/index.js#L22)
do not consider the possibility of `request.input` being string.

**Comment by secobarbital** [comment]
[src/index.js#L4](https://github.com/cyclejs/cycle-fetch-driver/blob/d2bae7eeaa9d0b29f1bc5f62f4b3686b5a966f35/src/index.js#L4) does, and normalizes it into the object structure so that downstream we don't have to switch.

**Comment by teohhanhui** [comment]
No it doesn't. That only handles the case of `request` (what's emitted to the driver) itself being a string. It doesn't handle cases where `request.input` is string (one would expect that to be acceptable if we were to follow the spec).

**Comment by teohhanhui** [comment]
And we should probably rename `input` to `request` in `normalizeRequest` to avoid confusion.

**Comment by secobarbital** [comment]
Agree on renaming `input` to `request` in `normalizeRequest` but not the object format. It is an imperfect representation of a list of arguments to `fetch` so I took the liberty of breaking the overloaded first argument into separate `url` and `input` keys.

If we took an array instead I would agree, but then we would need a way to attach the key. Another way I had considered was to call it `request` instead of `input` since it is a `Request` object, but `request.request` gets kinda recursive. I had the same issue with `route` in the routing libraries too.

I guess that's why naming variables is one of the two hard problems in CS ;)

**Comment by teohhanhui** [comment]
> It is an imperfect representation of a list of arguments to fetch so I took the liberty of breaking the overloaded first argument into separate `url` and `input` keys.

What about `fetchSpec` with `url`, `request` (because it really is a `Request` object) and `options` keys?

> If we took an array instead I would agree, but then we would need a way to attach the key.

That's what I tried to do just now, and of course I ran into the same issue... :stuck_out_tongue:

**Comment by secobarbital** [comment]
Feel free to do a PR so there's no doubt about what you mean. Now I actually kinda like the `args` array idea and may create a PR to discuss with you. And I haven't forgotten about the link to the spec and the examples of using `Request` object. Maybe you can reopen this one for those?

**Pull request closed without merging**
